### ISSUE TITLE
merak.exe using absolute install path of python.exe under the hood

### ISSUE THREAD

**Issue by Emmett-Brown82** [dave-msk/merak#15]
First of all, thanks for this amazing tool! It has spared us weeks of development and "reinventing the wheel".

We are incorporating part of our multi python versions compiling environment in a custom repository where merak is included.

Nevertheless, we are facing a bit tricky and annoying inconvenient: the "merak.exe" installed in ".\PythonXY\Scripts" folder is configured apparently during pip install with the absolute path of the pyhon.exe we are using. This is a big problem for us because it breaks portability and the fact that we can clone the repo in different root folders than the one used by the dev that installed merak for a custom specific python version.

We dont know how easy or tricky to change this is. We just thought it would be a "nice to have" and report it in order to get some feedback.

Use Case:
(1) python.exe pip install merak
(2) change the root directory where the PythonXY folder resides
(3) notice how the "merak.exe" command fails because it looks for the python.exe in the first installation absolute path.

Thanks in advance,
JC

**Comment by dave-msk** [comment]
Thanks for the detailed description. I'll take a look and see what I can do

**Comment by Emmett-Brown82** [comment]
Thanks Dave,
It really is an awesome tool.

**Comment by dave-msk** [comment]
This is a path problem which originates from how Python command-line wrapper is built by the packaging mechanism. `merak` has indicated `setuptools` to include a CLI wrapper via the `console_scripts` argument in `setup.py`. When the package is installed, it creates a wrapper script that calls the Python interpreter in the Python environment that `merak` is installed to. There are two scenarios:

1. The wrapper is located outside of the target Python environment folder
2. The wrapper is located within such folder

In the 1st case, it makes sense for the script to use absolute path as otherwise it has no knowledge on where to find the correct interpreter.

In the 2nd case, it actually resembles [this problem](https://stackoverflow.com/questions/20095351/shebang-use-interpreter-relative-to-the-script-path) where the shebangs generated by `setuptools` is not relative to the script file location at all

In either, the issue is not `merak` specific and there's not much I'm able to deal with it. But for your use case, I'll suggest building a Docker image for your building pipeline and run `merak` from there

**Comment by Emmett-Brown82** [comment]
Hi Dave,
I understand it is not a merak concern, but rather the way setuptools receives the python executable. 
I was wondering if we could tweak the setuptools package to force it to include a relative path to the python exe.
Could you pin point where these changes should occur in the setuptools package? preferably in a Python39 installation dir?

Thanks in advance!

**Comment by dave-msk** [comment]
I'm afraid I'm not the right person to answer the question as I'm not familiar with the implementation details of `setuptools`.

I noticed that there are Windows containers available for Docker which I think might be of help in your case. Please take a look at https://hub.docker.com/_/microsoft-windows-base-os-images
